#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define DRIVETRAIN_I2C 0xA5
#define ENVIRONMENT_I2C 0xA6

#define CMD_NONE 0x00

#define CMD_DRIVETRAIN_DRIVE 0x01
#define CMD_DRIVETRAIN_STOP 0x02
#define CMD_DRIVETRAIN_TURN 0x03
#define CMD_DRIVETRAIN_SET_VELOCITY 0x04
#define CMD_DRIVETRAIN_SET_TURN_VELOCITY 0x05
#define CMD_DRIVETRAIN_MOVE 0x06

#define DRIVETRAIN_DIRECTION_FORWARD 1
#define DRIVETRAIN_DIRECTION_BACKWARD 2

#endif